version: '3.9'

networks:
  pb_idm:

services:
  nginx:
    image: nginx:stable-alpine
    container_name: nginx_pb_idm
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:pro
      - ./nginx/logs/nginx:/var/logs/nginx:rw
    volumes_from:
      - php
    depends_on:
      - php
    networks:
      - pb_idm
  php:
    image: php:8.1-fpm-alpine
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_pb_idm
    tty: true
    volumes:
      - ./:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - pb_idm
